apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-files
  namespace: airflow
  labels:
    app: airflow-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi